apiVersion: apps/v1
kind: Deployment #we are creating a deployment
metadata:
  name: myapp-deployment #name of th deployment
spec:
  replicas: 3 #inside this deployment it will create three pod how the deployment is going to manage this three pod
  selector:
    matchLabels: #this is like an match expression
      app: myapp3 #key: value
  template: #inside the pod we need to create container. 
    metadata:
      name: myapp3-pod
      labels: #whatver label we have given to the pod same label name should exist inside your template. 
        app: myapp3
    spec:
      containers:
      - name: myapp3-container
        image: stacksimplify/kubenginx:3.0.0
        ports:
          - containerPort: 80

          #it has create pod
          #inside the pod it download an image 
          #finally start the container